var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
myString = 'Hello World';
myNum = 22;
myBool = true;
myVar = 1;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
console.log(strArr);
